### ISSUE TITLE
Language color issue

### ISSUE THREAD

**Issue by megabugman** [horsicq/Nauz-File-Detector#13]
Hi please consider changing the color, I almost cannot read it. thanks.

![image](https://user-images.githubusercontent.com/17204819/136130455-81ceb193-8058-46d1-ba7d-7415ae5279d4.png)

**Comment by horsicq** [comment]
Thank you for the report! It will be fixed in the next version!

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/StaticScan/commit/f369ddf34f88984c419bb7b5f6cd947bb816d9a0
