### ISSUE TITLE
Renaming the "operating system" output?

### ISSUE THREAD

**Issue by DLKSASDl** [horsicq/Nauz-File-Detector#14]
First of all I really like your tools and I appreciate the time and effort you put into developing them. 

I was wondering about the "operation system" output by Nauz. By looking at the code it appears that the OS result for PE files is calculated by parsing the Major/MinorOperatingSystemVersion field of the Optional Header. My understanding of the PE format was, that those fields are like a "required minimum version" to run the file. I did some tests using legacy compilers (VS 05/08) running Windows XP SP3 and Win7 and had varying results (see attachment). Just by looking at the Nauz output some could think that "Operation system" refers to the OS Version used to build the file and not some arbitrary version number set by VS. Maybe it's best to rename the output to clear up the confusion. 

[results_vs.log](https://github.com/horsicq/Nauz-File-Detector/files/7598172/results_vs.log)

**Comment by horsicq** [comment]
Hello! Thanks a lot for you report! I fixed an improved the operation system output. You could see it if you will compile the project from sources or will wait new version. :)
