### ISSUE TITLE
Detect binaries linked using mold

### ISSUE THREAD

**Issue by Absolucy** [horsicq/Nauz-File-Detector#16]
I'd PR this myself, but I can't figure out where to PR it to.

The [mold](https://github.com/rui314/mold) linker will leave an identification string in the `.comment` section of an ELF file. Example from the readme:

```
readelf -p .comment <executable-file>

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
  [    2b]  mold 9a1679b47d9b22012ec7dfbda97c8983956716f7
```

**Comment by horsicq** [comment]
Hello Lucy! Nice to see you on GitHub! :)

Thanks a lot for the tip! I will add the linker to NFD.

BTW the ELF ".comment" detects are here https://github.com/horsicq/SpecAbstract/blob/master/specabstract.cpp#L13761

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/SpecAbstract/compare/86ce7897353b4ca5c3143a9bff63a48fb2620468...b0b223f3fb32c0b01490cff82f0dbf60305c3e3c?diff=split
