### ISSUE TITLE
Problem when using Ukrainian language

### ISSUE THREAD

**Issue by 3xp0rt** [horsicq/Nauz-File-Detector#18]
![nauz](https://user-images.githubusercontent.com/61662492/166644372-46205446-927d-40f0-96c0-123d0f4c5ab0.png)

**Comment by horsicq** [comment]
Thanks for the bugreport! I will fix it ASAP

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/StaticScan/compare/4593869042c420406106f42ffc12e62c396629ae...576627de50ce0155656304c29b30fbee2e8b4b9e#diff-02195b8094c5df823766d9e5ae3569a9f2e88367f2359b3369a672dd9c28c2d0
