### ISSUE TITLE
Wrong installation

### ISSUE THREAD

**Issue by kermitdafrog8** [horsicq/Nauz-File-Detector#19]
make install is putting the applications, icon and xpeviewer in the wrong place.  I set the prefix to /usr but it's installing in /

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will take a look.

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/Nauz-File-Detector/commit/11a5fbf85153aa3f963585c8b1e80767a5afd112
