### ISSUE TITLE
Crashes when opened on Mac OS

### ISSUE THREAD

**Issue by allanxp4** [horsicq/Nauz-File-Detector#4]
Hello!

Tried to use it today on Mac OS 10.15, but it crashes straight up on startup.

Here's the crash log:

https://pastebin.com/fZ8YHBf1

**Comment by horsicq** [comment]
Thanks a lot for the bugreporr! I ll check it.

**Comment by horsicq** [comment]
Fixed. https://github.com/horsicq/Nauz-File-Detector/releases/tag/0.04
