### ISSUE TITLE
[question] Difference b/w Nauz-File-Detector & Detect-it-easy ?

### ISSUE THREAD

**Issue by graysuit** [horsicq/Nauz-File-Detector#6]
It is file detector looks same like detect it easy,
What will be major difference you can describe ?

And thanks again for detect it easy lite,
I use it a lot times for my personal malware analysis.

**Comment by horsicq** [comment]
Thanks a lot for the message. Nice to hear you are using DiE in your projects.
I described the difference here: https://forum.exetools.com/showpost.php?p=115420&postcount=3

I am going to develop the both programs in parallel and I will make a new release of DiE(Version 3.00) in a  month.

**Comment by graysuit** [comment]
I am very happy while using DIE that makes my work so easy,

> [-] When adding new detection, you need to recompile the program. 

**I will recommend not to make code 100% compiled,
Yeah you are absolutely right that compiled code is faster.**

So I will suggest to convert all signatures from C++ to C#,
You can take advantage of windows builtin compiler for C#,
And C# is familiar with C++, Both have same syntax,
Whereas, C++ don't have builtin compiler in windows.
 
After then you compile all signatures files into dll using CMD:
```
"C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe" detect.cs -target:library
```
If you are new to csharp And want to test **detect.cs**:
```
using System;

namespace HelloWorld
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine("Now you can detect ZIP,PE or anything here. And load this dll from exe.");    
    }
  }
}
```

And after compilation this will generate dll, 
You can easily load these multiple dlls in signature directory for different detection,

**Using dll loading technique, Any one can build his/her dll using any language,
And then can contribute to this wonderful project by adding his detector dll.**

And again I am pretty impressed from your work.
I am feeling very motivated.
<img src="https://i.ibb.co/Mn3Ftw9/Capture.png">

**Comment by graysuit** [comment]
Sorry I forgot both NFD & DIE are for Linux + windows mac-OS,
So this strategy will only work for windows.

**Comment by horsicq** [comment]
Thank you for your kind words and new ideas. :)

**Comment by graysuit** [comment]
I am happy you care about low end pc,
DIE works well in low end pc But even you launched lite version that is super fast and simple,

I have seen all big projects like VLC,notepad++,Libreoffice etc
They are great but 1 con of their code is about not having simplicity,
VLC have 52 MB code files, How I do I read their code then ?
Absolutely I can't. My mind is of human. Not machine.  :)

But in DIE code I didn't find that con Even it is big project,
May be because you use low end pc or you have suffered from low end pc,
And thats why you care about us.

Well, I got the actual difference from the author,
So I am closing this issue,
I will like to see Nauz-File-Detector getting more powerfull,
My wishes are with you,
And again thank you for being open source developer.
Without open source, internet will be shutdown.
