### ISSUE TITLE
Some (chinese?) characters in filename not possible

### ISSUE THREAD

**Issue by MikeHofmann** [horsicq/Nauz-File-Detector#7]
We have an odd case with a sample containing some strange characters inside the filename: `loader表能点分析功.xlsx` (filename redacted by me).

When i start ```nauz --deepscan --json /sample/loader表能点分析功.xlsx``` i get an error:

```
Cannot find: /sample/loader??????????????????.xlsx
```

`nauz --version` is showing `Nauz File Detector 0.05alpha`

**Comment by horsicq** [comment]
Thanks a lot for the bugreport!

I cannot reproduce the issue.

I build NFD from the latest sources.
I made an Excel file with name "loader表能点分析功.xlsx" and tried to open in console version. It works.

**Comment by horsicq** [comment]
Did you try to open the file in any another console application?

**Comment by MikeHofmann** [comment]
> I build NFD from the lastest sources.

Ok, right. I checked i saw that my last build was from late may 2020. I'll rebuild, but so far my automated pipeline have evolved since then. Will take a day to lift everything. I'll retest and fill an update afterwards.

> Did you try to open the file in any another console application?

I'm abusing cicd pipelines for automated processing of new samples. Besides nauz i use `curl --upload-files sample.exe` to test against several APIs (vt, sandbox, multi-av solution) without any problem. So curl i able to process the weird filename. Another non-public cli-tool fails, having filed an issue over there as well.

**Comment by horsicq** [comment]
Thanks a lot for the information.
 If it will not work, please tell me the exact version of Qt and what the exact Operating System is. I will try to run it in a virtual machine.

**Comment by MikeHofmann** [comment]
OK, i tested with the latest commit. It works as intended. Sorry for bothering.

Had some trouble upping my build pipeline though. The Dockerfile is no longer valid with the latest changed (qt version requirement). I'll see that i pull an updated version soon.
